### ISSUE TITLE
Class Selection Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#11]
**Issue Description**: Attempting to select a class other than the default one simply does not work on this map. I have not tested other maps that use the class system yet to see if the issue is persistent. No errors are thrown to the console.

**Map**: MobArena: Silent City

**Video**:

https://github.com/chatasma/PGM/assets/72997300/0bbc08b9-ee1d-4f9b-a8c1-73f7c70a2394

**Stack Trace**: None

**Comment by chatasma** [comment]
Looks like this is caused by not having an equals implementation on the new MaterialData implementation. Fixed this by providing said implementation
