### ISSUE TITLE
Acacia Plank Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#12]
**Issue Description**: Upon loading a map that uses planks in the starter kit, it appears that the planks are always acacia planks. No errors are thrown to the console.

**Version**: [PGM-0.16-SNAPSHOT-8998d10d.jar](https://cdn.discordapp.com/attachments/810660676938235964/1241288190837395508/PGM-0.16-SNAPSHOT-8998d10d.jar?ex=664ba176&is=664a4ff6&hm=a0292c44ad3133b98b74850f2d95743bd01969441304a68d0ce4d4e106132b47&)

**Stack Trace**: None

**Comment by chatasma** [comment]
Seems like XSeries has "wood" (the item that is used for oak planks in many map XMLs) as an alias for acacia planks rather than oak, added an override for oak planks!
