### ISSUE TITLE
Chunk Loading Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#4]
**Issue Description**: Some map chunks appear to not be loading. On this map in particular, I've tested to confirm whether it is the exact same chunks that fail to load after a server restart/reload of the map, and I can indeed confirm it is the same chunks. I imagine this issue can happen on other maps as well.

**Map**: Knockout Stadium

**Screenshots**:
![Issue 4 S1](https://github.com/chatasma/PGM/assets/72997300/0bbccea1-e697-4afa-bebd-ff23453df7d6)
![Issue 4 S2](https://github.com/chatasma/PGM/assets/72997300/9efa9ed6-fe65-4782-8b22-ad51e6fbc22a)
![Issue 4 S3](https://github.com/chatasma/PGM/assets/72997300/f55a9a4e-7f46-41d7-849c-0a51027ee779)

**Comment by chatasma** [comment]
Seems to be happening in 1.13 but not 1.20
