### ISSUE TITLE
Helmet-slot Item Bug

### ISSUE THREAD

**Issue by Mew2K** [chatasma/PGM#5]
**Issue Description**: Dying on this map causes the stained-glass item equipped in the player's helmet slot to be dropped on the ground. This is not the intended behavior of the map. No errors are thrown to the console in regards to this bug.

**Map**: Cacti the RAGE

**Video**:

https://github.com/chatasma/PGM/assets/72997300/6835c1b7-e8b3-44c5-bf74-1fe6e557cd7f

**Stack Trace**: None

**Comment by chatasma** [comment]
Seems to not happen in 1.20

As for the issue with the stained glass not being colored that we discovered, it appears the way the color requirement was being encoded into the item was no longer working. The existing implementation encoded data into items by leveraging the item lore, unsure why this was no longer working in the new version, but I provided a new implementation for 1.20 to use the persistence APIs Bukkit now has, and can confirm that the glass is now being stained correctly
